### ISSUE TITLE
Dataset link down

### ISSUE THREAD

**Issue by ntomita** [gallardorafael/DIBaS-Dataset#1]
Hi @gallardorafael 

Thank you so much for providing the link to the dataset.

The data download link in the repository is currently unavailable, consistently returning a "404 Not Found" error. I kindly request your assistance in resolving this issue.

Could you please fix the data download link or provide an alternative method to access the data. This will greatly facilitate the use of the repository. I can alternatively provide a file drop link where you can upload the dataset if that's convenient for you.

Best,
Naofumi

**Comment by gallardorafael** [comment]
Hi, 

I don't have the rights to redistribute the dataset. However, I have verified that the sub-links I posted in the repo are working.

To download the dataset:
1. Check the links here: https://github.com/gallardorafael/DIBaS-Dataset#links-to-each-species-as-the-original-web-page
2. Download each species one by one (I know it is not as easy as we would like, but is the only way to do it)
3. Extract the zip files, each zip file corresponds to one species in the DIBaS dataset. 
4. Now you have the full DIBaS dataset.

Can you confirm this worked for you?

**Comment by ntomita** [comment]
Hi @gallardorafael ,

Perfect, thanks for your very quick response! I have clicked a few and the links seems working. I will download all files and check the integrity, and let you know if I see any issues!

Best,
Naofumi

**Comment by ntomita** [comment]
Closing as we confirmed no issues with files.
